name: ci

on:
  push:
    branches: [main, dev]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B builds/ci -DCMAKE_BUILD_TYPE=Release
      - name: Build
        run: cmake --build builds/ci -j
